### ISSUE TITLE
odd error, cannot run

### ISSUE THREAD

**Issue by 0xClandestine** [0xKitsune/solstat#12]
Command:
```rust
solstat --path ./src
```

Error:
```rust
thread 'main' panicked at 'Unable to read overview.md: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/solstat-0.1.0/src/report/optimization_report.rs:16:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by 0xKitsune** [comment]
I noticed this today actually. I think it is because it is looking for the `overview.md` file with a relative path rather than an absolute path. I will update this shortly and close the issue when it is all patched up! Thanks for opening the issue.

**Comment by 0xClandestine** [comment]
> I noticed this today as well actually. I think it is because it is looking for the `overview.md` file with a relative path rather than an absolute path. I will update this shortly and close the issue when it is all patched up (should be good to go tomorrow afternoon)! Thanks for opening the issue.

Absolutely, awesome project btw!

**Comment by 0xKitsune** [comment]
Just pushed a new version to crates.io with a patch. I am going to close this issue but let me know if you are still encountering errors.
