### ISSUE TITLE
Panic on immutable variables

### ISSUE THREAD

**Issue by gakonst** [0xKitsune/solstat#35]
this line panics https://github.com/0xKitsune/solstat/blob/main/src/analyzer/optimizations/immutable_variables.rs#L218

```
git clone https://github.com/Rari-Capital/vaults
cd vaults
solstate --path ./src
```

**Comment by 0xKitsune** [comment]
Thanks for opening an issue, Ill check it out shortly and get a patch in progress!

**Comment by 0xKitsune** [comment]
Just a quick update on this. I identified the issue and am currently working on a patch. It should be merged later today/tomorrow.
