### ISSUE TITLE
Improper sizes returned by `get_type_size`

### ISSUE THREAD

**Issue by LHerskind** [0xKitsune/solstat#39]
The `get_type_size` seems to return invalid sizes, the comment states that it returns the size in bytes, but it returns the size in bits. 

- it returns 256 bits for `address` and `payable` which both are 160 bits only
- the `bytesx` returns `x*4` but should be `x*8` to have the proper size, currently it believes that two `bytes24` could be packed in the same storage slot.
- a bool is stored with a whole byte, so should return 8 bits instead. To go down to only a single bit needs some bitpacking.

**Comment by 0xKitsune** [comment]
Thanks for opening this and submitting a PR. Just merged to development and will merge to main soon!
